apps/signature_captures/urls.py
from django.urls import re_path

from .api_views import (
    APISignatureCaptureDetailView, APISignatureCapturesImageView,
    APISignatureCaptureListView
)
from .views import (
    SignatureCaptureCreateView, SignatureCaptureDeleteView,
    SignatureCaptureDetailView, SignatureCaptureEditView,
    SignatureCaptureListView
)

urlpatterns_documents = [
    re_path(
        route=r'^documents/(?P<document_id>\d+)/signature_captures/$',
        name='signature_capture_list',
        view=SignatureCaptureListView.as_view()
    ),
    re_path(
        route=r'^documents/(?P<document_id>\d+)/signature_captures/create/$',
        name='signature_capture_create',
        view=SignatureCaptureCreateView.as_view()
    )
]

urlpatterns_signature_captures = [
    re_path(
        route=r'^signature_captures/(?P<signature_capture_id>\d+)/delete/$',
        name='signature_capture_delete',
        view=SignatureCaptureDeleteView.as_view()
    ),
    re_path(
        route=r'^signature_captures/(?P<signature_capture_id>\d+)/detail/$',
        name='signature_capture_detail',
        view=SignatureCaptureDetailView.as_view()
    ),
    re_path(
        route=r'^signature_captures/(?P<signature_capture_id>\d+)/edit/$',
        name='signature_capture_edit',
        view=SignatureCaptureEditView.as_view()
    )
]

urlpatterns = []
urlpatterns.extend(urlpatterns_documents)
urlpatterns.extend(urlpatterns_signature_captures)

api_urls = [
    re_path(
        route=r'^documents/(?P<document_id>[0-9]+)/signature_captures/$',
        name='signature_capture-list',
        view=APISignatureCaptureListView.as_view()
    ),
    re_path(
        route=r'^documents/(?P<document_id>[0-9]+)/signature_captures/(?P<signature_capture_id>[0-9]+)/$',
        name='signature_capture-detail',
        view=APISignatureCaptureDetailView.as_view()
    ),
    re_path(
        route=r'^documents/(?P<document_id>[0-9]+)/signature_captures/(?P<signature_capture_id>[0-9]+)/image/$',
        name='signature_capture-image',
        view=APISignatureCapturesImageView.as_view()
    )
]

apps/signature_captures/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _

from mayan.apps.common.validators import validate_internal_name
from mayan.apps.databases.model_mixins import ExtraDataModelMixin
from mayan.apps.documents.models.document_models import Document
from mayan.apps.events.decorators import method_event
from mayan.apps.events.event_managers import (
    EventManagerMethodAfter, EventManagerSave
)

from .events import (
    event_signature_capture_created, event_signature_capture_deleted,
    event_signature_capture_edited
)
from .managers import ValidSignatureCaptureManager
from .model_mixins import SignatureCaptureBusinessLogicMixin


class SignatureCapture(
    ExtraDataModelMixin, SignatureCaptureBusinessLogicMixin, models.Model
):
    document = models.ForeignKey(
        on_delete=models.CASCADE, related_name='signature_captures',
        to=Document, verbose_name=_(message='Document')
    )
    data = models.TextField(
        blank=True, help_text=_(
            message='Data representing the handwritten signature.'
        ), verbose_name=_(message='Signature capture data')
    )
    svg = models.TextField(
        blank=True, help_text=_(
            message='Vector representation of the handwritten signature.'
        ), verbose_name=_(message='SVG signature capture data')
    )
    text = models.CharField(
        help_text=_(message='Print version of the captured signature.'),
        max_length=224, verbose_name=_(message='Text')
    )
    user = models.ForeignKey(
        on_delete=models.CASCADE, related_name='signature_captures',
        to=settings.AUTH_USER_MODEL, verbose_name=_(message='User')
    )
    date_time_created = models.DateTimeField(
        auto_now_add=True, db_index=True,
        verbose_name=_(message='Date and time created')
    )
    date_time_edited = models.DateTimeField(
        auto_now=True, db_index=True,
        verbose_name=_(message='Date and time edited')
    )
    internal_name = models.CharField(
        db_index=True, help_text=_(
            message='This value will be used when referencing this signature '
            'capture in relationship to the document. Can only contain '
            'letters, numbers, and underscores.'
        ), max_length=255, validators=[validate_internal_name],
        verbose_name=_(message='Internal name')
    )

    objects = models.Manager()
    valid = ValidSignatureCaptureManager()

    class Meta:
        ordering = ('-date_time_created',)
        unique_together = ('document', 'internal_name')
        verbose_name = _(message='Signature capture')
        verbose_name_plural = _(message='Signature captures')

    def __str__(self):
        return '{} - {}'.format(
            self.text, self.get_date_time_created()
        )

    @method_event(
        action_object='self',
        event=event_signature_capture_deleted,
        event_manager_class=EventManagerMethodAfter,
        target='document'
    )
    def delete(self, *args, **kwargs):
        self.cache_partition.delete()
        return super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            kwargs={'signature_capture_id': self.pk},
            viewname='signature_captures:signature_capture_detail'
        )

    @method_event(
        event_manager_class=EventManagerSave,
        created={
            'actor': 'user',
            'action_object': 'document',
            'event': event_signature_capture_created,
            'target': 'self'
        },
        edited={
            'action_object': 'document',
            'event': event_signature_capture_edited,
            'target': 'self'
        }
    )
    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)

apps/signature_captures/templates/signature_captures/widget_signature_capture.html
{% load i18n %}

<style>
.signature-pad-wrapper {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
      -ms-flex-direction: column;
          flex-direction: column;
    font-size: 10px;
    height: 460px;
    padding: 2px;
    position: relative;
}

.signature-pad-body {
    -webkit-box-flex: 1;
      -ms-flex: 1;
          flex: 1;
    border: 1px solid #f4f4f4;
    position: relative;
}

.signature-pad-body canvas {
    border-radius: 4px;
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100%;
}

.signature-pad-footer {
    margin-top: 8px;
}

.form-control {
    height: 100%;
    width: 100%;
}

.input-group {
    width: 100%;
}

#id_data {
    display: none;
    position: absolute;
    visibility: hidden;
}
</style>

<div class="input-group">
    {% include 'django/forms/widgets/input.html'  %}

    <div class="form-control">
        <div id="signature-pad-wrapper" class="signature-pad-wrapper">
            <div class="signature-pad-body">
                <canvas></canvas>
            </div>
            <div class="signature-pad-footer">
                <div class="description text-center text-small">{% trans 'Sign above' %}</div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function() {
        $('#id_data').hide();

        const $fieldPointValues = $('.signature-captures-capture-data');
        const $fieldSVG = $('.signature-captures-capture-svg');

        const elementSignaturePadWrapper = document.getElementById('signature-pad-wrapper');
        const elementSignaturePadCanvas = elementSignaturePadWrapper.querySelector('canvas');

        const signaturePad = new SignaturePad(elementSignaturePadCanvas, {});

        function doSignatureReload() {
            if ($fieldPointValues.val()) {
                let signaturePadPointValues = $fieldPointValues.val();
                if (signaturePadPointValues) {
                    signaturePad.fromData(
                        JSON.parse(signaturePadPointValues)
                    );
                }
            }
        }

        function doSignatureDownload() {
            $fieldPointValues.val(
                JSON.stringify(
                    signaturePad.toData()
                )
            );

            $fieldSVG.val(
                signaturePad.toDataURL('image/svg+xml')
            );
        }

        function resizeCanvas() {
          let windowRatio =  Math.max(window.devicePixelRatio || 1, 1);

          elementSignaturePadCanvas.width = elementSignaturePadCanvas.offsetWidth * windowRatio;
          elementSignaturePadCanvas.height = elementSignaturePadCanvas.offsetHeight * windowRatio;
          elementSignaturePadCanvas.getContext('2d').scale(windowRatio, windowRatio);
          signaturePad.clear();
          doSignatureReload();
        }

        signaturePad.addEventListener('endStroke', () => {
            doSignatureDownload();
        });
        window.onresize = resizeCanvas;

        resizeCanvas();
    });
</script>